# The buildpacks key is at the root level, same as 'services'
buildpacks:
  - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest

services:
  # This is our main web server
  - type: web
    name: universal-downloader
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    # No buildpacks key here anymore
    envVars:
      # Sets the python version
      - key: PYTHON_VERSION
        value: 3.11.4